### ISSUE TITLE
I get this error when I execute mentalist, Can you please help me?

### ISSUE THREAD

**Issue by maldonado82h** [sc0tfree/mentalist#17]
mentalist
Traceback (most recent call last):
  File "/usr/local/bin/mentalist", line 11, in <module>
    load_entry_point('Mentalist==1.0', 'gui_scripts', 'mentalist')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/Mentalist-1.0-py3.8.egg/mentalist/controller.py", line 20, in <module>
    from . import view
  File "/usr/local/lib/python3.8/dist-packages/Mentalist-1.0-py3.8.egg/mentalist/view/__init__.py", line 1, in <module>
    from .adder import AdderNode
  File "/usr/local/lib/python3.8/dist-packages/Mentalist-1.0-py3.8.egg/mentalist/view/adder.py", line 7, in <module>
    from .base_words import BaseWordsNode, center_window
  File "/usr/local/lib/python3.8/dist-packages/Mentalist-1.0-py3.8.egg/mentalist/view/base_words.py", line 8, in <module>
    from .main import center_window
  File "/usr/local/lib/python3.8/dist-packages/Mentalist-1.0-py3.8.egg/mentalist/view/main.py", line 15, in <module>
    locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
  File "/usr/lib/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by hackwithharsha** [comment]
@maldonado82h what is your system configuration like operating sytem, 32 bit or 64 bit etc..,

**Comment by sh1va73** [comment]
I have the same error. How to fix this error? I have 64bit, Kali 2020.2.

**Comment by sh1va73** [comment]
Open : etc/locale.gen
uncomment: en_US.UTF-8 UTF-8
run: locale-gen
