### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by sms1sis** [sc0tfree/mentalist#37]
v 1.0
by sc0tfree

Traceback (most recent call last):
  File "/usr/local/bin/mentalist", line 33, in <module>
    sys.exit(load_entry_point('Mentalist==1.0', 'gui_scripts', 'mentalist')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Mentalist-1.0-py3.11.egg/mentalist/controller.py", line 368, in main
    controller = Controller()
                 ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Mentalist-1.0-py3.11.egg/mentalist/controller.py", line 31, in __init__
    self.mainview = view.MainWindow(self)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Mentalist-1.0-py3.11.egg/mentalist/view/main.py", line 163, in __init__
    size[1] = h - 10
    ~~~~^^^
TypeError: 'tuple' object does not support item assignment

**Comment by minhquan38** [comment]
It's because of your resolution, I try 1920:1080 and the error disappears. 
From the previous issue, people try to change the code to stretch the resolution so I just decided to change my resolution instead of the code.
